// Canonical exploration project contract. The preview copy is generated by tools/sync_exploration.mjs.
import {universeFields} from './universe-fields.mjs';
const coverHosts=new Set(['cdn.weread.qq.com','wfqqreader-1252317822.image.myqcloud.com']);
export function coverUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&coverHosts.has(url.hostname)&&!url.username&&!url.password?url.href:'';}catch{return '';}}
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const list=(v,max,label)=>{if(!Array.isArray(v)||v.length>max)throw Error(`${label}格式不正确或超过数量限制。`);return v;};
const text=(v,max=20000,required=false)=>{if(typeof v!=='string'||v.length>max||required&&!v.trim())throw Error('有一处文字缺失或超过长度限制。');return v;};
const optional=(v,max=20000)=>typeof v==='string'?text(v,max):'';
const ident=(v,node=false,max=200)=>{const s=String(v??'');if(!s||s.length>max||/[|\u0000-\u001f]/.test(s)||['__proto__','constructor','prototype'].includes(s)||node&&!/^[A-Za-z0-9_-]+$/.test(s))throw Error('标识缺失或含不支持的字符。');return s;};
const strings=v=>Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string'&&x.trim()).slice(0,100).map(x=>text(x,100)))]:[];
export const FORMAT='reading-atlas-workspace';
export function materialLabel(e){const kind=({highlight:'划线',review:'书评',card:'读书卡',note:'笔记'})[e.kind]||'材料';return e.sourceLocator?.ordinal?`${kind} ${e.sourceLocator.ordinal}`:e.source||kind;}
export function findEvidence(p,q){
  const book=p.books.find(b=>b.id===q?.bookId&&b.included!==false),evidence=book?.evidence.find(e=>e.id===q?.evidenceId&&e.included!==false);
  return evidence&&typeof q.excerpt==='string'&&q.excerpt.trim()&&evidence.text.includes(q.excerpt)?{book,evidence}:null;
}
function normalizeEvidence(items,bookId){
  const seen=new Set();return list(items,2000,'单书材料').map((item,i)=>{
    if(!object(item))throw Error('材料条目必须是对象。');
    const id=ident(item.id??`${bookId}:e${i}`,false,250);if(seen.has(id))throw Error('同一本书内材料标识重复。');seen.add(id);
    const e={id,text:text(item.text??item.markText??item.content,100000,true),kind:['highlight','review','card','note'].includes(item.kind)?item.kind:'highlight',included:item.included!==false};
    if(item.source)e.source=optional(item.source,500);
    if(object(item.sourceLocator)){
      e.sourceLocator={};const s=item.sourceLocator;
      if(Number.isSafeInteger(s.ordinal)&&s.ordinal>0)e.sourceLocator.ordinal=s.ordinal;
      if(typeof s.bookmarkId==='string')e.sourceLocator.bookmarkId=text(s.bookmarkId,200);
    }else if(item.bookmarkId)e.sourceLocator={ordinal:i+1,bookmarkId:optional(item.bookmarkId,200)};
    return e;
  });
}
function inlineEvidence(b){
  if(b.evidence!=null)return b.evidence;
  const result=[];
  for(const [field,kind]of [['highlights','highlight'],['annotations','note'],['notes','note']])if(Array.isArray(b[field])){
    for(const item of b[field])result.push(typeof item==='string'?{text:item,kind}:{...item,kind});
  }
  const review=b.myReview??b.review,content=typeof review==='string'?review:review?.content??review?.text??review?.abstract;
  if(typeof content==='string'&&content.trim())result.push({text:content,kind:'review',source:'本人书评'});
  return result;
}
function normalizeTheme(t,p){
  if(!object(t))throw Error('线索主题必须是对象。');
  const b={id:ident(t.id,true)};
  if(['ai-draft','curated'].includes(t.basis))b.basis=t.basis;
  for(const k of ['name','title','opening','entry','endTitle','endBody'])b[k]=text(t[k],k==='name'?100:12000,true);
  b.start=ident(t.start,true);
  b.nodes=list(t.nodes,200,'主题线索').map(n=>{
    if(!object(n)||!object(n.quote))throw Error('线索必须有可回查的引文。');
    const out={id:ident(n.id,true)};
    for(const k of ['title','subtitle','context','observation'])out[k]=text(n[k],12000,true);
    out.quote={bookId:ident(n.quote.bookId),evidenceId:ident(n.quote.evidenceId,false,250),excerpt:text(n.quote.excerpt,20000,true)};
    if(!findEvidence(p,out.quote))throw Error(`「${b.name}」有引文找不到原材料、与原文不符，或指向已排除内容。`);
    out.choices=list(n.choices,12,'线索方向').map(c=>({target:ident(c.target,true),label:text(c.label,300,true),hint:text(c.hint,2000,true),bridge:text(c.bridge,12000,true)}));
    if(new Set(out.choices.map(c=>c.target)).size!==out.choices.length)throw Error('同一处线索不能重复指向相同方向。');
    return out;
  });
  const nodes=new Map(b.nodes.map(n=>[n.id,n]));
  if(nodes.size!==b.nodes.length||!nodes.has(b.start))throw Error('线索起点缺失或标识重复。');
  for(const n of b.nodes)for(const c of n.choices)if(!nodes.has(c.target))throw Error('有一个探索方向没有对应线索。');
  const reached=new Set(),visit=id=>{if(reached.has(id))return;reached.add(id);nodes.get(id).choices.forEach(c=>visit(c.target));};visit(b.start);
  if(reached.size!==nodes.size)throw Error('主题里有无法从开场到达的线索。');
  return b;
}
// Strictly rebuild saved state; neither unknown fields nor credentials are carried into packages.
export function normalizeJourney(raw,themes){
  if(raw==null)return {activeTheme:themes[0]?.id||'',sessions:[]};
  if(!object(raw))throw Error('探索记录格式不正确。');
  const result={activeTheme:optional(raw.activeTheme,200),sessions:[]},seen=new Set();
  for(const s of list(raw.sessions??[],100,'探索记录')){
    const t=themes.find(t=>t.id===s?.theme);if(!t||seen.has(s.theme))throw Error('记录中的主题缺失或重复。');seen.add(s.theme);
    const nodes=new Map(t.nodes.map(n=>[n.id,n])),found=new Set();
    const steps=list(s.steps,80,'探索来路').map((step,i)=>{
      if(!object(step)||!nodes.has(step.id))throw Error('探索来路包含不存在的线索。');
      if(i===0&&(step.id!==t.start||step.kind!=='start'||step.from))throw Error('探索来路的起点不正确。');
      if(i){
        if(step.kind==='follow'){
          if(step.from!==s.steps[i-1].id||!nodes.get(step.from)?.choices.some(c=>c.target===step.id))throw Error('探索来路包含不存在的连接。');
        }else if(step.kind!=='revisit'||step.from||!found.has(step.id))throw Error('探索回看记录不正确。');
      }
      found.add(step.id);return {id:step.id,from:step.from||null,kind:step.kind};
    });
    if(!steps.length||!Number.isInteger(s.at)||s.at<0||s.at>=steps.length)throw Error('探索当前位置不正确。');
    const pins=list(s.pins??[],200,'保留的线索').map(id=>{if(!found.has(id))throw Error('保留的线索尚未发现。');return id;});
    const noteIds=new Set(),notes=list(s.notes??[],200,'个人笔记').map(pair=>{
      if(!Array.isArray(pair)||pair.length!==2||!found.has(pair[0])||noteIds.has(pair[0]))throw Error('个人笔记的线索不存在或重复。');noteIds.add(pair[0]);return [pair[0],text(pair[1],2000)];
    });
    result.sessions.push({theme:t.id,steps,at:s.at,pins:[...new Set(pins)],notes,revisiting:s.revisiting===true});
  }
  if(result.activeTheme&&!themes.some(t=>t.id===result.activeTheme))throw Error('当前位置引用了不存在的主题。');
  return result;
}
export function normalizeProject(input){
  if(!object(input))throw Error('请选择包含书目的项目文件。');
  if(input.format&&!['reading-universe-private','reading-universe-public',FORMAT].includes(input.format))throw Error('暂不支持这个项目格式。');
  if(input.version!=null&&input.version!==1)throw Error('暂不支持这个版本，请保留原文件。');
  const seen=new Set();let materialCount=0;
  const p={format:FORMAT,version:1,name:optional(input.name,150)||'我的阅读项目',books:[],exploration:{version:1,themes:[]}};
  p.books=list(input.books,1500,'书目').filter(b=>!b?.mergedInto).map(b=>{
    if(!object(b))throw Error('书目条目必须是对象。');
    const id=ident(b.id??b.bookId);if(seen.has(id))throw Error('书目标识重复，请检查项目。');seen.add(id);
    const out={id,title:text(b.title,300,true),author:optional(b.author,300),cover:coverUrl(b.cover),included:b.included!==false,tags:strings(input.universe?.edits?.books?.[id]?.tags??input.edits?.books?.[id]?.tags??input.universe?.analysis?.[id]?.tags??input.analysis?.[id]?.tags??b.tags)};
    const numeric=v=>Number.isFinite(Number(v))?Math.max(0,Number(v)):0;
    Object.assign(out,{readingTime:numeric(b.readingTime),notes:numeric(typeof b.notes==='object'?b.notes?.total:b.notes),finished:Boolean(b.finished??b.finishTime),finishTime:optional(b.finishTime==null?'':String(b.finishTime),80),rating:optional(b.rating==null?(b.affectionScore==null?'':String(b.affectionScore)):String(b.rating),80)});
    out.evidence=normalizeEvidence(inlineEvidence(b),id);
    // Keep already generated reading cards as local source material, not fabricated introductions.
    const card=input.edits?.cards?.[id]??input.cards?.[id];
    if(typeof card==='string'&&card.trim()&&!out.evidence.some(e=>e.kind==='card'&&e.text===card)){
      let cid=`${id}:card`;while(out.evidence.some(e=>e.id===cid))cid+='-';out.evidence.push({id:cid,text:text(card,100000,true),kind:'card',included:true});
    }
    list(out.evidence,2000,'单书材料');materialCount+=out.evidence.length;
    if(materialCount>100000)throw Error('材料数量过多，请分成不同项目。');
    return out;
  });
  if(!p.books.length)throw Error('项目至少需要一本书。');
  if(input.exploration!=null){
    if(!object(input.exploration)||input.exploration.version!==1)throw Error('探索内容版本不受支持。');
    p.exploration.themes=list(input.exploration.themes,100,'探索主题').map(t=>normalizeTheme(t,p));
    if(new Set(p.exploration.themes.map(t=>t.id)).size!==p.exploration.themes.length)throw Error('探索主题标识重复。');
  }
  p.journey=normalizeJourney(input.journey,p.exploration.themes);
  const metadata=object(input.universe)?input.universe:input;
  p.universe=universeFields(metadata,p.books);
  p.universe.bookTags=Object.fromEntries(p.books.map(b=>[b.id,strings(metadata.bookTags?.[b.id]??input.books.find(raw=>String(raw.id??raw.bookId)===b.id)?.tags)]));
  return p;
}
export function packageProject(p,journey){return normalizeProject({...p,journey});}
export function projectFromFiles(files){
  const entries=Object.entries(files),json=[];
  for(const [name,value] of entries)if(/\.json$/i.test(name)){try{json.push([name,JSON.parse(value)]);}catch{throw Error(`「${name}」不是有效的 JSON。`);}}
  let candidates=json.filter(([,p])=>object(p)&&p.format===FORMAT);
  if(!candidates.length)candidates=json.filter(([,p])=>object(p)&&p.format==='reading-universe-private');
  if(!candidates.length)candidates=json.filter(([name,p])=>/(^|\/)books\.json$/i.test(name)&&Array.isArray(p?.books));
  if(!candidates.length)candidates=json.filter(([,p])=>Array.isArray(p?.books));
  if(candidates.length!==1)throw Error(candidates.length?'找到多份项目或书目，请一次导入一份。':'没有找到书目，请选择项目 JSON，或含 books.json 的资料文件夹。');
  const [mainName,main]=candidates[0];
  if(main.format)return normalizeProject(main);
  const base=mainName.slice(0,mainName.lastIndexOf('/')+1);
  const tags=json.find(([name])=>name===base+'theme_tags.json')?.[1];
  const result={books:main.books.map(b=>{
    const id=String(b.id??b.bookId),out={...b};
    const cached=json.find(([name])=>name===base+`highlights/${id}.json`)?.[1];
    out.evidence=inlineEvidence(b);
    if(cached){const hs=Array.isArray(cached)?cached:cached.highlights??cached.items;
      if(!Array.isArray(hs))throw Error(`《${b.title}》的划线文件格式不正确。`);
      out.evidence=[...out.evidence,...hs.map((e,i)=>({id:`${id}:h${i+1}`,text:e.markText??e.text,kind:'highlight',included:e.included!==false,sourceLocator:{ordinal:i+1,bookmarkId:e.bookmarkId}}))];
    }
    const reviews=json.find(([name])=>name===base+`reviews/${id}.json`)?.[1];
    const rs=Array.isArray(reviews)?reviews:reviews?.reviews;
    if(Array.isArray(rs))out.evidence=[...out.evidence,...rs.map((r,i)=>({id:`${id}:r${i+1}`,text:r.content??r.text??r.review?.content,kind:'review',included:r.included!==false})).filter(r=>typeof r.text==='string'&&r.text.trim())];
    const note=files[base+`notes/${id}.md`];if(typeof note==='string'&&note.trim())out.evidence.push({id:`${id}:local-note`,text:note,kind:'note'});
    return out;
  }),analysis:object(tags)?tags:{},cards:{}};
  for(const b of result.books){const id=String(b.id??b.bookId),value=files[base+`cards/${id}.md`];if(typeof value==='string')result.cards[id]=value;}
  return normalizeProject(result);
}
